# Generated by Django 3.0.5 on 2020-06-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.TextField(),
        ),
    ]
